@apiurl_1 = http://localhost:8000/api
@apiurl_2 = https://crm-laravel-api.herokuapp.com/api
@access_token = {{login.response.body.$.data.access_token}}

###
GET {{apiurl_1}}
Content-Type: application/json

###
# @name login
POST {{apiurl_1}}/login
Content-Type: application/json

{  
    "email": "recep_1@gmail.com",
    "password": "123456"
}

###
POST {{apiurl_1}}/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "methodName": "SelectByColumns",
    "data": {
        "cusStatus": true,
        "first_name": "ali"
    }   
}

###
POST {{apiurl_1}}/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "methodName": "SelectByKey",
    "data": {
        "id":"2256"
    }
}

###
POST {{apiurl_1}}/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "methodName": "Insert",
    "data": {
        "first_name": "recep5",
        "phone": 5449128008
    }
}

###
POST {{apiurl_1}}/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "methodName": "Update",
    "data": {
        "id":"2252",
        "first_name": "recep3",
        "phone": 5449128008
    }
}

###
POST {{apiurl_1}}/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "methodName": "Delete",
    "data": {
        "id":"1563"
    }
}

###
POST {{apiurl_1}}/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{   
    "methodName": "SelectCustomerStatistics",
    "data": {
        //"userId":"1111",
        "isActive" : true,
        "chartNo": 1 
    }
}


###
POST {{apiurl_1}}/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{   
    "methodName": "TransferRecords",
    "data": {
        "userId":"1111" 
    }
}


###
GET {{apiurl_1}}/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
GET {{apiurl_1}}/customers/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
POST {{apiurl_1}}/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "first_name": "Ali",
    "last_name": "Veli",
    "phone": "5441234567",
    "email": "ali@gmail.com",
    "tc_no": "123456789012"
}

###
PUT {{apiurl_1}}/customers/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
     "first_name": "Ali 2"
}

###
DELETE  {{apiurl_1}}/customers/1
Content-Type: application/json
Authorization: Bearer {{access_token}}
